# Generated by Django 5.2.7 on 2025-10-28 21:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('asin', models.CharField(help_text='Amazon Standard Identification Number', max_length=10, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(help_text='Título del producto', max_length=500)),
                ('brand', models.CharField(blank=True, help_text='Marca del producto', max_length=100, null=True)),
                ('image_url', models.URLField(blank=True, help_text='URL de la imagen principal del producto', max_length=500, null=True)),
                ('current_price_new', models.DecimalField(blank=True, decimal_places=2, help_text='Precio actual del producto nuevo (en centavos)', max_digits=10, null=True)),
                ('current_price_amazon', models.DecimalField(blank=True, decimal_places=2, help_text='Precio actual vendido por Amazon (en centavos)', max_digits=10, null=True)),
                ('current_price_used', models.DecimalField(blank=True, decimal_places=2, help_text='Precio actual del producto usado (en centavos)', max_digits=10, null=True)),
                ('sales_rank_current', models.IntegerField(blank=True, help_text='Sales Rank actual del producto', null=True)),
                ('rating', models.DecimalField(blank=True, decimal_places=2, help_text='Calificación promedio del producto (0-5)', max_digits=3, null=True)),
                ('review_count', models.IntegerField(blank=True, help_text='Número total de reseñas', null=True)),
                ('price_history', models.JSONField(default=dict, help_text='Historial completo de precios en formato JSON')),
                ('last_updated', models.DateTimeField(auto_now=True, help_text='Última vez que se actualizó la información')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación del registro')),
                ('queried_by', models.ForeignKey(help_text='Usuario que consultó el producto', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['-last_updated'],
            },
        ),
    ]
