# Generated by Django 5.2.7 on 2025-10-28 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='availability_amazon',
            field=models.IntegerField(default=0, help_text='Disponibilidad en Amazon (0=No disponible, 1=Disponible)'),
        ),
        migrations.AddField(
            model_name='product',
            name='binding',
            field=models.CharField(blank=True, help_text='Tipo de producto (Electronics, Books, etc.)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.JSONField(default=list, help_text='Lista de categorías del producto'),
        ),
        migrations.AddField(
            model_name='product',
            name='category_tree',
            field=models.JSONField(default=list, help_text='Árbol de categorías del producto'),
        ),
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, help_text='Color del producto', max_length=100, null=True),
        ),
    ]
