# Generated by Django 5.2.7 on 2025-10-28 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_availability_amazon_product_binding_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rating_history',
            field=models.JSONField(default=dict, help_text='Historial de calificaciones en formato JSON'),
        ),
        migrations.AddField(
            model_name='product',
            name='reviews_data',
            field=models.JSONField(default=dict, help_text='Datos de reseñas en formato JSON'),
        ),
        migrations.AddField(
            model_name='product',
            name='sales_rank_history',
            field=models.JSONField(default=dict, help_text='Historial de sales rank en formato JSON'),
        ),
    ]
