# Generated by Django 5.2.7 on 2025-10-28 23:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_rating_history_product_reviews_data_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_price', models.DecimalField(decimal_places=2, help_text='Precio objetivo en centavos', max_digits=10)),
                ('price_type', models.CharField(choices=[('new', 'Precio Nuevo'), ('amazon', 'Precio Amazon'), ('used', 'Precio Usado')], default='new', help_text='Tipo de precio a monitorear', max_length=10)),
                ('frequency', models.IntegerField(choices=[(4, '4 veces al día (cada 6 horas)'), (2, '2 veces al día (cada 12 horas)'), (1, '1 vez al día (cada 24 horas)')], default=2, help_text='Frecuencia de verificación')),
                ('is_active', models.BooleanField(default=True, help_text='Si la alerta está activa')),
                ('triggered', models.BooleanField(default=False, help_text='Si ya se disparó la alerta')),
                ('triggered_at', models.DateTimeField(blank=True, help_text='Fecha y hora cuando se disparó la alerta', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación de la alerta')),
                ('last_checked', models.DateTimeField(blank=True, help_text='Última vez que se verificó esta alerta', null=True)),
                ('product', models.ForeignKey(help_text='Producto a monitorear', on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('user', models.ForeignKey(help_text='Usuario que crea la alerta', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Alerta de Precio',
                'verbose_name_plural': 'Alertas de Precio',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'product', 'price_type', 'target_price')},
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('price_alert', 'Alerta de Precio'), ('system', 'Sistema'), ('info', 'Información'), ('warning', 'Advertencia')], default='info', help_text='Tipo de notificación', max_length=20)),
                ('title', models.CharField(help_text='Título de la notificación', max_length=200)),
                ('message', models.TextField(help_text='Mensaje completo de la notificación')),
                ('is_read', models.BooleanField(default=False, help_text='Si la notificación fue leída')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación de la notificación')),
                ('user', models.ForeignKey(help_text='Usuario destinatario', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('alert', models.ForeignKey(blank=True, help_text='Alerta relacionada (si aplica)', null=True, on_delete=django.db.models.deletion.CASCADE, to='products.pricealert')),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-created_at'],
            },
        ),
    ]
