# Generated by Django 5.2.7 on 2025-11-01 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_pricealert_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ai_summary',
            field=models.TextField(blank=True, help_text='Resumen generado por IA del historial de precios', null=True),
        ),
    ]
