# Generated by Django 5.2.7 on 2025-11-01 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_ai_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ai_summary_generated_at',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora cuando se generó el resumen de IA', null=True),
        ),
    ]
