# Generated by Django 5.2.7 on 2025-11-05 02:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_ai_summary_generated_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BestSellerSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.CharField(help_text='ID de la categoría de Amazon', max_length=50)),
                ('category_search', models.CharField(help_text='Término de búsqueda o nombre de la categoría', max_length=200)),
                ('category_name', models.CharField(blank=True, help_text='Nombre completo de la categoría (si está disponible)', max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de la búsqueda')),
                ('user', models.ForeignKey(help_text='Usuario que realizó la búsqueda', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Búsqueda de Best Sellers',
                'verbose_name_plural': 'Búsquedas de Best Sellers',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='products_be_user_id_730c48_idx')],
            },
        ),
    ]
